site:
  title: "DRAFT: Commodore Documentation"
  url: http://localhost/
  start_page: commodore::index.adoc
content:
  sources:
  - url: .                 # The current folder is a git repo
    branches: HEAD         # "HEAD" uses whichever branch is currently checked out
    start_path: docs
    edit_url: 'https://github.com/projectsyn/commodore/edit/master/{path}'
ui:
  bundle:
    url: https://github.com/vshn/antora-ui-default/releases/download/1.4/ui-bundle.zip
    snapshot: false
asciidoc:
  attributes:
    toc: 'auto'
    toc-title: ''
    toclevels: 2
    hide-uri-scheme: ''
    experimental: ''
    stem: ''
    kroki-server-url: https://vshn-kroki.appuioapp.ch
  extensions:
  - asciidoctor-kroki
output:
  destinations:
  - provider: fs
    path: ./_antora
    clean: true
